### ISSUE TITLE
[Question] ARF(Automatic Frame Rate) Supported ?

### ISSUE THREAD

**Issue by michalss** [media-kit/media-kit#315]
Hi,
Is ARF(Automatic Frame Rate) supported please ? Mostly releated to mobile platforms..

` AFR (auto frame rate) – is function which designed to match the media player's output frame rate to the original frame rate of (video) content. This applies to content that's mastered at different frame rates, for example 24fps film-based content or other international video content encoded at 60, 50, 30, 25, and 24fps.`

Some more exmaplanation why is needed..
https://tvbox-app.com/en/autoframerate/
https://ugoos.com/system-auto-frame-rate-for-tv-boxes

Regards

**Comment by sbenmeddour** [comment]
You must create or use an existing plugin to change framerate. 

Active display (screen) framerate can only be changed with platform specific code, and cannot be changed with low level code from mpv

[Doc for android](https://developer.android.com/media/optimize/performance/frame-rate

**Comment by alexmercerind** [comment]
It's necessary to configure things on libmpv side as well. It will control the rate at which callback from `mpv_render_context_set_update_callback` gets called (& thus FPS). FYI: [`--override-display-fps`](https://mpv.io/manual/stable/#options-override-display-fps).

On Flutter side, [`package:flutter_displaymode`](https://pub.dev/packages/flutter_displaymode) seems to be a good choice.

**Comment by alexmercerind** [comment]
Still, not sure how big of a difference it will make. By default, video's FPS will be used. I don't think any issue will surface.

**Comment by sbenmeddour** [comment]
> Still, not sure how big of a difference it will make. By default, video's FPS will be used. I don't think any issue will surface.

I'm not sure (didn't tested) if video playback will be as smooth as a display with same refresh rate of video

Example: Play a video with 24.0 FPS on a 60 FPS display can show "micro stuttering"

**Comment by alexmercerind** [comment]
Displaying a 24 FPS video on 60 FPS display will be fine AFAIK (all video players do it the same). But displaying a video that has higher/near FPS to the display, can definitely cause tearing.

**Comment by michalss** [comment]
It is a huge difference, shuttering is a real thing unfortunately..

**Comment by alexmercerind** [comment]
Provide clear details.

It's not "performance" if the frame rate is actually being limited. What are you even saying?

**Comment by michalss** [comment]
OK let me explain. I did some testing with video file 1920x1080 HEVC/MJPEG+AC3 and size 2.8 GB, i need to mention i worked with PC so far. I know media kit is mpv based, so i made sample application in flutter, turn HW accc on and test this video file. It works, playing, but you can see is shuttering video on certain parts.  So i took MPVnet and test it in there and play is very smoot and working perfectly. There must be some different with implelentation for sure...

**Comment by alexmercerind** [comment]
WHICH PLATFORM?

**Comment by michalss** [comment]
so far i did test only PC...

**Comment by alexmercerind** [comment]
Microsoft Windows?

**Comment by michalss** [comment]
Yes. this different can be seen by eyes clearly...

**Comment by alexmercerind** [comment]
Is it this specific media?

**Comment by michalss** [comment]
OK her you go... take it pls i need to remove it after you got it...
`https://11.dl.wsfiles.cz/8159/M6mgjrORxV/524288000/eJw1jsFKw0AQQP9lDp5CMrPJbrMLxQ8QUxDUS0A23dk2Yo1M0kYq_ruj4PE9Zt7MF0QIQOhLQltaWxIZKGCEgAUsEMh5QjSNUbwoFnCG4BAbW8D8xx8QFjlzAe8aOsRjEuY1r5k5ayipdH4grC0OqakJs7bIbDy1G4pNdtHUbfKt4f3vuJ6Ey5h4epkX4XhSJ6pWHuZjFC73177K4xv31b07HV5l9_D51Fe3LDLJ9rG763bP3c201bVF_h+brxCMd97Z1nnz_QPAiEM3/77bde53701323cfd7d2da5b5c8dfbf69b0f9f34a/gahdreewfwfeef`

**Comment by michalss** [comment]
you will see it cleary on the start of the media with cinematics.. its really a huge different...

**Comment by michalss** [comment]
also comapred with VLC, same thing vlc,mpvnet works ok, media kit is not

**Comment by michalss** [comment]
BTW i have millions of this examples if you need to. I can privately share a huge lib of all formats...

**Comment by alexmercerind** [comment]
My Ryzen 3 2200U is taking around 10% CPU, this isn't a performance issue clearly.

I can't really see the difference either. If I play a higher FPS video, I feel everything is smoother (which is an indication of everything working as intended).

https://github.com/alexmercerind/flutter-windows-ANGLE-OpenGL-ES/assets/28951144/32637cc3-05e2-4918-8f68-8fa5ba343fcf

https://github.com/alexmercerind/flutter-windows-ANGLE-OpenGL-ES/assets/28951144/240ee195-5133-4848-ba58-44262e9926b8

There can be a number of things that I'd like to add:
- mpv uses --vo=d3d11va, which is overall more efficient.
- Flutter's content is also rendered like a "game engine" using [OpenGL ES 2.0 through ANGLE](https://github.com/google/angle).
  - The video rendering in media_kit is done through this mechanism:
    https://github.com/Microsoft/angle/wiki/Interop-with-other-DirectX-code
  - AFAIK you can see "micro-stutters" on Flutter's own UI (besides the video).

You can subscribe to #296 for direct D3D11VA/DXVA2 rendering on Windows; if we feel the requirement. Further details are present there. That still does not guarantee any changes in experience, since there's a significant interop/syncing involved.

In your C#/.NET, if you embed a native HWND, you'd face airspace issues. This is certainly better than that.

You are free to play around with libmpv options yourself e.g. adding --override-display-fps=60 here:
https://github.com/media-kit/media-kit/blob/e5ab431183c81272e0a5545fb791273d751dbd8e/media_kit_video/windows/video_output.cc#L35-L36

Let us know if you find a sweet spot, everyone will be helped.

**Comment by alexmercerind** [comment]
Lastly... make sure you're in release mode :)

**Comment by michalss** [comment]
Ok thx for test, but im 100% sure of it. i send it to more ppl if they can confirm this..


https://github.com/media-kit/media-kit/assets/1000729/684f26ce-d91b-409d-8e29-ab4b3ceb3222

**Comment by alexmercerind** [comment]
You can join our Discord server (where we talk development), it'll be easier to communicate there:

[![](https://img.shields.io/discord/1079685977523617792?color=33cd57&label=Discord&logo=discord&logoColor=discord)](https://discord.gg/h7qf2R9n57)

**Comment by michalss** [comment]
Thx a lo I will...

**Comment by alexmercerind** [comment]
We'd need details to find out a fix. And... We're committed.
