### ISSUE TITLE
The full screen of vertical video cannot be occupied

### ISSUE THREAD

**Issue by sofm13** [media-kit/media-kit#317]
so like this player,but the full screen of vertical video cannot be occupied

**Comment by alexmercerind** [comment]
Share sample, specify platform. It's not as easy as it seems.

**Comment by alexmercerind** [comment]
In new update, you can pass `onEnterFullscreen` & `onExitNativeFullscreen` to `Video` to change the behavior e.g. orientation, status-bar, fullscreen etc. etc.

```dart
Video(
  controller: controller,
  onEnterFullscreen: () async {
    // TODO: Handle enter fullscreen.
  },
  onExitFullscreen: () async {
    // TODO: Handle exit fullscreen.
  },
);
```

Refer to "Installation" section of the README for updating.

<hr>

You might wanna keep our default functions to some modifications:

https://github.com/media-kit/media-kit/blob/769829c5c56c30216db646ba426c81ffb9368a39/media_kit_video/lib/src/video/video_texture.dart#L294-L343

**Comment by alexmercerind** [comment]
I'm not interested in overcomplicating the current implementation of video controls. It is fine, highly customizable & good in terms of behavior & looks. In case you want to change the behavior extensively in order to match the very specific demands of your project, you might wanna consider writing them from scratch (our README has a section explaining that too).
