### ISSUE TITLE
App does not build on linux

### ISSUE THREAD

**Issue by Wachu985** [media-kit/media-kit#357]
**First of all thanks for your work:**
I am using Manjaro KDE to run the application. I have followed all the steps in the README and I have everything installed. I am using version 3.10.6 of Flutter and version 0.36.0 of mpv. Everything is installed correctly and I have compiled other linux apps fine so far. Thanks in advance

### Logs
`Launching lib/main.dart on Linux in debug mode...
main.dart:1
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
Exception: Build process failed
Exited`

**Comment by alexmercerind** [comment]
https://github.com/media-kit/media-kit/actions/runs/5799504452/job/15719647940

**Comment by alexmercerind** [comment]
Sorry can't help. Not enough details. Our CI succeeds & I can build locally.

**Comment by TheOneWithTheBraid** [comment]
This issue is caused by the line https://github.com/media-kit/media-kit/blob/main/libs/linux/media_kit_libs_linux/linux/CMakeLists.txt#L93

It looks like the CMAKE related variables set by Flutter for the plugin build are not passed over to the `mimalloc` build unless they are globally declared around.

Yep, GitHub actions do not seem to encounter this issue, but in a plain Debian Docker image I can reproduce it.

**Comment by TheOneWithTheBraid** [comment]
https://github.com/media-kit/media-kit/blob/main/libs/linux/media_kit_libs_linux/linux/CMakeLists.txt#L95

> add_subdirectory() is too much work. Alternatively building it through command line.

I guess here's the response. @alexmercerind I'd kindly ask to reopen this issue since it's now clear how it's caused (and reproducible).

I guess the most meaningful way to shim mimalloc would be simply depending on the system-provided mimalloc for linking ?

- `libmimalloc-dev` is packaged on Debian
- `mimalloc` is packaged on Arch

And likely any other Linux distribution too.
