### ISSUE TITLE
[Windows] Build Failure

### ISSUE THREAD

**Issue by robhageboeck** [media-kit/media-kit#404]
Had to do a flutter upgrade from 3.3.10 to 3.7.12 because of the following error:
```
Building Windows application...                                 
CMake Error at flutter/ephemeral/.plugin_symlinks/media_kit_libs_windows_video/windows/CMakeLists.txt:30 (message):
  mpv-dev-x86_64-20230201-git-7990dd8.7z integrity check failed.


Unable to generate build files
```
Even with much more recent packages I get the following error:
```
CMake Error at flutter/ephemeral/.plugin_symlinks/media_kit_libs_windows_video/windows/CMakeLists.txt:74 (message):
  mpv-dev-x86_64-20230719-git-140ec21.7z integrity check failed.
```

Currently pinning versions as below, have tried `media_kit_libs_windows_video: 1.0.2` as well. As far as I can tell the above mentioned file has been deleted. I can't go any higher than the listed versions because of other dependency issues. I had to bump because the original release I was on (from 6 months ago) had its mpv library deleted as well.
```
  media_kit: 1.0.0
  media_kit_video: 1.0.0
  media_kit_native_event_loop: 1.0.6
  media_kit_libs_windows_video: 1.0.4
```

Need a stable version to build from - can not build the app without the libs_windows package in CI/CD

**Comment by alexmercerind** [comment]
Why can't you go to higher versions? 

What issue do you face when resolving dependencies?

**Comment by alexmercerind** [comment]
I admit that this is an inconvenience created due to my default & older binaries for Windows should've been kept in place. I apologise & promise that this won't happen in future & older releases will be kept.

At the moment, only latest version of package:media_kit_libs_windows_video _i.e._ 1.0.7 is supported & will build correctly. There are major advancements in latest version including many bug-fixes & most importantly, the bundle size has been nearly halved. So, the only way out of this situation is to bump all of your packages [to versions stated in the "Installation" section](https://github.com/media-kit/media-kit#installation). As far as I understand, this is the part where you're having a conflict, to solve that you can make use of [`dependency_overrides` in your pubspec.yaml](https://dart.dev/tools/pub/dependencies#dependency-overrides). This will allow you to force version for the packages which are having the conflict.

I'm ready to provide any assistance or further help if required.

Thanks!
