### ISSUE TITLE
Cannot find media_kit_libs_video on pub.dev

### ISSUE THREAD

**Issue by gibahjoe** [media-kit/media-kit#446]
Hi, so If i search for ```media_kit_libs_video``` on pub.dev, I cannot find it again, or these 
```
  media_kit_libs_ios_video: ^1.1.2               # iOS package for video native libraries.
  media_kit_libs_macos_video: ^1.1.2             # macOS package for video native libraries.
  media_kit_libs_windows_video: ^1.0.6           # Windows package for video native libraries.
  media_kit_libs_linux: ^1.1.0                   # GNU/Linux dependency package.
```

were they removed or are they no longer necessary? if so, from what version of ```media_kit``` and can the documentation be updated to reflect this?

**Comment by alexmercerind** [comment]
You can simply visit:

https://pub.dev/packages/media_kit_libs_video

There's no issue.

<hr>

You can still depend upon previous packages if you wish to, in-fact `media_kit_libs_video` depends on these packages internally & zero code/implementation in it. However, I will recommend to simply depend on `media_kit_libs_video` directly. I made this change because it was kind-of tedious & annoying for users to specify versions of each package manually.

Thanks!

**Comment by alexmercerind** [comment]
All packages other than package:media_kit are marked as "UNLISTED".

It didn't seem like a good idea to cram the website with all media_kit packages. The users are expected to only visit the primary package's page where all the relevant documentation, code samples & other instructions are mentioned.

**Comment by gibahjoe** [comment]
Thank you.
