### ISSUE TITLE
controls screen not rebuild on fullscreen

### ISSUE THREAD

**Issue by mhkarami** [media-kit/media-kit#459]
[in windows platform]
I want to show a custom view on video . for example i defined a variable that save play pause count  and want to show in center of screen :
```
class _VideoPlayScreenState ... {
  var playPauseCount = 0;
```

change variable : 
```
    player.stream.playing.listen(
      (bool playing) {
        setState(() {
          playPauseCount++;
          isPlaying = playing;
        });
        debugPrint("_isPlaying = ${playing} playPauseCount : $playPauseCount");
      },
    );
```
video widget: 
```
....
child: Video(
          controller: _controller,
          controls: (VideoState videoState) {
            return Stack(
              children: [
                MaterialDesktopVideoControls(videoState),
                Align(
                  alignment: Alignment.center,
                  child: Text("$playPauseCount"),
                ),
              ],
            );
          },
        ),
```
it works fine on normal state (any time i press play or puse button playPauseCount inscrease and Text widget in center of player show new value) but after I press full-screen button the playPauseCount variable changes with play-pause, but Text not rebuild and just show old value. After I press full-screen button again and minimize screen it works fine again and updated value appears again.
is this a bug of the library or is my mistake in using library?

**Comment by alexmercerind** [comment]
It's not a bug in library.

**Comment by alexmercerind** [comment]
I'm just going to clear some doubts:

<hr>

Whenever you enter fullscreen, a new route is created (similar to `Navigator.of(context).push(MaterialPageRoute(...))`) & that route creates a fresh `Video` widget which has nearly same properties as your original (non-fullscreen) `Video` widget. So, because it's a different screen/page.

You must look how Flutter lifecycle behaves & I believe it's intentional.

<hr>

Do not use `player.stream.playing` to identify play count. The stream will fire if you play/pause/playOrPause. The better idea will be to simply increment your count in your play button logic (instead of relying on stream).
