### ISSUE TITLE
[Bug Report][Windows] GPU usage in idle state

### ISSUE THREAD

**Issue by Jhonfunk** [media-kit/media-kit#472]
os: windows 11

- There is a constant 8% gpu usage in the state where  the video is not even starting to play
- There is a constant 15% gpu usage when the video is finished playing or stopped or paused

This could causes the laptop to drain the battery too quickly

**Comment by alexmercerind** [comment]
I can confirm, there's GPU usage in idle state on Windows. I'm yet to find the cause.

**Comment by NotAgentBilly** [comment]
Seems this may be due to https://github.com/media-kit/media-kit/blob/ac336385a689d963ae0d19c0901917cf5991d6de/media_kit_video/lib/media_kit_video_controls/src/controls/material.dart#L946C1-L946C1

While the CircularProgressIndicator is set to 0 opacity its actually still animating.

The following fix works but I assume Visibility doesn't wait for the animation.

```dart
Visibility(
  visible: buffering,
  child: AnimatedOpacity(
      curve: Curves.easeInOut,
      opacity: buffering ? 1.0 : 0.0,
      duration: _theme(context)
          .controlsTransitionDuration,
      child: _theme(context)
              .bufferingIndicatorBuilder
              ?.call(context) ??
          const Center(
            child: CircularProgressIndicator(
              color: Color(0xFFFFFFFF),
            ),
          )),
),
```

**Comment by alexmercerind** [comment]
I further improvised in #453. It will be part of next stable release.

Thanks!

**Comment by alexmercerind** [comment]
@Jhonfunk @NotAgentBilly 

A new update has been released. Please refer to the ["Installation" section of the README](https://github.com/media-kit/media-kit#installation).

Thanks!
