### ISSUE TITLE
Linux issue:     collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by oniangel12933** [media-kit/media-kit#550]
When I tried to use this package for linux, it always show the error.
`    collect2: error: ld returned 1 exit status`
How can I fix this issue?
#linux #collect2

**Comment by alexmercerind** [comment]
Share output of flutter run --verbose.

**Comment by kekko7072** [comment]
@alexmercerind  Same issue, 
I'm new to this package,  i was using the example project (media_kit_test) and i was getting error a Cmake error due to miss installation of `libmpv-dev`. Then after successfullyu installation using `sudo apt install libmpv-dev` i faced this error:     `collect2: error: ld returned 1 exit status`

This is flutter run --verbose:

**Comment by alexmercerind** [comment]
Hi @kekko7072 & @oniangel12933,

Most likely you guys are using snap installation of Flutter. Please use the manual installation:

https://docs.flutter.dev/get-started/install/linux#method-2-manual-installation

**Comment by alexmercerind** [comment]
Unlike other platforms, media_kit on GNU/Linux uses user installation of libmpv (how most GNU/Linux distributions work; dependent on packages from distribution). On other platforms, you don't need any additional steps other than editing `pubspec.yaml` like usual.

**Comment by kekko7072** [comment]
@alexmercerind  i reinstalled using manual installation but i'm still facing issue.

**Comment by alexmercerind** [comment]
Try to do a `flutter clean` & check if `flutter doctor` reports any issues. I don't see anything media_kit specific in the logs.

Thanks!

**Comment by kekko7072** [comment]
I run 'flutter clean' and 'flutter doctor' with no problems.
<details><summary>flutter run --verbose</summary>

`
[  +39 ms] executing: uname -m
[   +4 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +95 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required,
skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[  +69 ms] executing: /home/francesco/Android/Sdk/platform-tools/adb devices -l
[  +82 ms] List of devices attached
[   +7 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping
update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required,
skipping update.
[ +113 ms] Connected devices:
[  +58 ms] Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS
6.2.0-35-generic
[   +2 ms] Chrome (web)    • chrome • web-javascript • Google Chrome
118.0.5993.88
[   +1 ms] [1]: Linux (linux)
[        ] [2]: Chrome (chrome)
[   +1 ms] Please choose one (or "q" to quit)
[        ] : 
[+1585 ms] 1
[  +25 ms] Skipping pub get: version match.
[  +84 ms] Found plugin file_picker at
/home/francesco/.pub-cache/hosted/pub.dev/file_picker-5.5.0/
[  +12 ms] Found plugin flutter_plugin_android_lifecycle at
/home/francesco/.pub-cache/hosted/pub.dev/flutter_plugin_android_lifecycle-2.0.1
6/
[  +21 ms] Found plugin package_info_plus at
/home/francesco/.pub-cache/hosted/pub.dev/package_info_plus-4.2.0/
[  +15 ms] Found plugin path_provider at
/home/francesco/.pub-cache/hosted/pub.dev/path_provider-2.1.1/
[   +6 ms] Found plugin path_provider_android at
/home/francesco/.pub-cache/hosted/pub.dev/path_provider_android-2.2.0/
[   +5 ms] Found plugin path_provider_foundation at
/home/francesco/.pub-cache/hosted/pub.dev/path_provider_foundation-2.3.1/
[   +4 ms] Found plugin path_provider_linux at
/home/francesco/.pub-cache/hosted/pub.dev/path_provider_linux-2.2.1/
[   +5 ms] Found plugin path_provider_windows at
/home/francesco/.pub-cache/hosted/pub.dev/path_provider_windows-2.2.1/
[  +12 ms] Found plugin screen_brightness at
/home/francesco/.pub-cache/hosted/pub.dev/screen_brightness-0.2.2+1/
[   +4 ms] Found plugin screen_brightness_android at
/home/francesco/.pub-cache/hosted/pub.dev/screen_brightness_android-0.1.0+2/
[   +5 ms] Found plugin screen_brightness_ios at
/home/francesco/.pub-cache/hosted/pub.dev/screen_brightness_ios-0.1.0/
[   +3 ms] Found plugin screen_brightness_macos at
/home/francesco/.pub-cache/hosted/pub.dev/screen_brightness_macos-0.1.0+1/
[   +5 ms] Found plugin screen_brightness_windows at
/home/francesco/.pub-cache/hosted/pub.dev/screen_brightness_windows-0.1.3/
[  +26 ms] Found plugin volume_controller at
/home/francesco/.pub-cache/hosted/pub.dev/volume_controller-2.0.7/
[  +12 ms] Found plugin wakelock_plus at
/home/francesco/.pub-cache/hosted/pub.dev/wakelock_plus-1.1.3/
[  +12 ms] Found plugin media_kit_libs_android_video at
/home/francesco/Desktop/media-kit-main/libs/android/media_kit_libs_android_video
/
[   +3 ms] Found plugin media_kit_libs_ios_video at
/home/francesco/Desktop/media-kit-main/libs/ios/media_kit_libs_ios_video/
[   +3 ms] Found plugin media_kit_libs_linux at
/home/francesco/Desktop/media-kit-main/libs/linux/media_kit_libs_linux/
[   +3 ms] Found plugin media_kit_libs_macos_video at
/home/francesco/Desktop/media-kit-main/libs/macos/media_kit_libs_macos_video/
[   +4 ms] Found plugin media_kit_libs_windows_video at
/home/francesco/Desktop/media-kit-main/libs/windows/media_kit_libs_windows_video
/
[   +7 ms] Found plugin media_kit_native_event_loop at
/home/francesco/Desktop/media-kit-main/media_kit_native_event_loop/
[   +8 ms] Found plugin media_kit_video at
/home/francesco/Desktop/media-kit-main/media_kit_video/
[  +90 ms] Found plugin file_picker at
/home/francesco/.pub-cache/hosted/pub.dev/file_picker-5.5.0/
[   +4 ms] Found plugin flutter_plugin_android_lifecycle at
/home/francesco/.pub-cache/hosted/pub.dev/flutter_plugin_android_lifecycle-2.0.1
6/
[  +16 ms] Found plugin package_info_plus at
/home/francesco/.pub-cache/hosted/pub.dev/package_info_plus-4.2.0/
[   +6 ms] Found plugin path_provider at
/home/francesco/.pub-cache/hosted/pub.dev/path_provider-2.1.1/
[   +2 ms] Found plugin path_provider_android at
/home/francesco/.pub-cache/hosted/pub.dev/path_provider_android-2.2.0/
[   +2 ms] Found plugin path_provider_foundation at
/home/francesco/.pub-cache/hosted/pub.dev/path_provider_foundation-2.3.1/
[   +2 ms] Found plugin path_provider_linux at
/home/francesco/.pub-cache/hosted/pub.dev/path_provider_linux-2.2.1/
[   +4 ms] Found plugin path_provider_windows at
/home/francesco/.pub-cache/hosted/pub.dev/path_provider_windows-2.2.1/
[   +8 ms] Found plugin screen_brightness at
/home/francesco/.pub-cache/hosted/pub.dev/screen_brightness-0.2.2+1/
[   +3 ms] Found plugin screen_brightness_android at
/home/francesco/.pub-cache/hosted/pub.dev/screen_brightness_android-0.1.0+2/
[   +2 ms] Found plugin screen_brightness_ios at
/home/francesco/.pub-cache/hosted/pub.dev/screen_brightness_ios-0.1.0/
[   +1 ms] Found plugin screen_brightness_macos at
/home/francesco/.pub-cache/hosted/pub.dev/screen_brightness_macos-0.1.0+1/
[   +3 ms] Found plugin screen_brightness_windows at
/home/francesco/.pub-cache/hosted/pub.dev/screen_brightness_windows-0.1.3/
[  +13 ms] Found plugin volume_controller at
/home/francesco/.pub-cache/hosted/pub.dev/volume_controller-2.0.7/
[   +3 ms] Found plugin wakelock_plus at
/home/francesco/.pub-cache/hosted/pub.dev/wakelock_plus-1.1.3/
[   +7 ms] Found plugin media_kit_libs_android_video at
/home/francesco/Desktop/media-kit-main/libs/android/media_kit_libs_android_video
/
[   +2 ms] Found plugin media_kit_libs_ios_video at
/home/francesco/Desktop/media-kit-main/libs/ios/media_kit_libs_ios_video/
[   +2 ms] Found plugin media_kit_libs_linux at
/home/francesco/Desktop/media-kit-main/libs/linux/media_kit_libs_linux/
[   +2 ms] Found plugin media_kit_libs_macos_video at
/home/francesco/Desktop/media-kit-main/libs/macos/media_kit_libs_macos_video/
[   +3 ms] Found plugin media_kit_libs_windows_video at
/home/francesco/Desktop/media-kit-main/libs/windows/media_kit_libs_windows_video
/
[   +4 ms] Found plugin media_kit_native_event_loop at
/home/francesco/Desktop/media-kit-main/media_kit_native_event_loop/
[   +4 ms] Found plugin media_kit_video at
/home/francesco/Desktop/media-kit-main/media_kit_video/
[  +56 ms] Found plugin file_picker at
/home/francesco/.pub-cache/hosted/pub.dev/file_picker-5.5.0/
[   +1 ms] Found plugin flutter_plugin_android_lifecycle at
/home/francesco/.pub-cache/hosted/pub.dev/flutter_plugin_android_lifecycle-2.0.1
6/
[   +4 ms] Found plugin package_info_plus at
/home/francesco/.pub-cache/hosted/pub.dev/package_info_plus-4.2.0/
[   +2 ms] Found plugin path_provider at
/home/francesco/.pub-cache/hosted/pub.dev/path_provider-2.1.1/
[   +2 ms] Found plugin path_provider_android at
/home/francesco/.pub-cache/hosted/pub.dev/path_provider_android-2.2.0/
[   +1 ms] Found plugin path_provider_foundation at
/home/francesco/.pub-cache/hosted/pub.dev/path_provider_foundation-2.3.1/
[   +1 ms] Found plugin path_provider_linux at
/home/francesco/.pub-cache/hosted/pub.dev/path_provider_linux-2.2.1/
[   +2 ms] Found plugin path_provider_windows at
/home/francesco/.pub-cache/hosted/pub.dev/path_provider_windows-2.2.1/
[   +4 ms] Found plugin screen_brightness at
/home/francesco/.pub-cache/hosted/pub.dev/screen_brightness-0.2.2+1/
[   +1 ms] Found plugin screen_brightness_android at
/home/francesco/.pub-cache/hosted/pub.dev/screen_brightness_android-0.1.0+2/
[   +1 ms] Found plugin screen_brightness_ios at
/home/francesco/.pub-cache/hosted/pub.dev/screen_brightness_ios-0.1.0/
[   +1 ms] Found plugin screen_brightness_macos at
/home/francesco/.pub-cache/hosted/pub.dev/screen_brightness_macos-0.1.0+1/
[   +3 ms] Found plugin screen_brightness_windows at
/home/francesco/.pub-cache/hosted/pub.dev/screen_brightness_windows-0.1.3/
[   +7 ms] Found plugin volume_controller at
/home/francesco/.pub-cache/hosted/pub.dev/volume_controller-2.0.7/
[   +1 ms] Found plugin wakelock_plus at
/home/francesco/.pub-cache/hosted/pub.dev/wakelock_plus-1.1.3/
[   +3 ms] Found plugin media_kit_libs_android_video at
/home/francesco/Desktop/media-kit-main/libs/android/media_kit_libs_android_video
/
[        ] Found plugin media_kit_libs_ios_video at
/home/francesco/Desktop/media-kit-main/libs/ios/media_kit_libs_ios_video/
[        ] Found plugin media_kit_libs_linux at
/home/francesco/Desktop/media-kit-main/libs/linux/media_kit_libs_linux/
[   +1 ms] Found plugin media_kit_libs_macos_video at
/home/francesco/Desktop/media-kit-main/libs/macos/media_kit_libs_macos_video/
[   +1 ms] Found plugin media_kit_libs_windows_video at
/home/francesco/Desktop/media-kit-main/libs/windows/media_kit_libs_windows_video
/
[   +1 ms] Found plugin media_kit_native_event_loop at
/home/francesco/Desktop/media-kit-main/media_kit_native_event_loop/
[   +3 ms] Found plugin media_kit_video at
/home/francesco/Desktop/media-kit-main/media_kit_video/
[ +105 ms] Generating
/home/francesco/Desktop/media-kit-main/media_kit_test/android/app/src/main/java/
io/flutter/plugins/GeneratedPluginRegistrant.java
[ +187 ms] Initializing file store
[  +15 ms] Skipping target: gen_localizations
[   +6 ms] gen_dart_plugin_registrant: Starting due to
{InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/home/francesco/Desktop/media-kit-main/media_kit_test/.dart_tool/package_config_
subset,/home/francesco/Desktop/media-kit-main/media_kit_test/.dart_tool/flutter_
build/dart_plugin_registrant.dart}
[  +22 ms] Found plugin file_picker at
/home/francesco/.pub-cache/hosted/pub.dev/file_picker-5.5.0/
[   +4 ms] Found plugin flutter_plugin_android_lifecycle at
/home/francesco/.pub-cache/hosted/pub.dev/flutter_plugin_android_lifecycle-2.0.1
6/
[   +5 ms] Found plugin package_info_plus at
/home/francesco/.pub-cache/hosted/pub.dev/package_info_plus-4.2.0/
[   +2 ms] Found plugin path_provider at
/home/francesco/.pub-cache/hosted/pub.dev/path_provider-2.1.1/
[   +1 ms] Found plugin path_provider_android at
/home/francesco/.pub-cache/hosted/pub.dev/path_provider_android-2.2.0/
[   +1 ms] Found plugin path_provider_foundation at
/home/francesco/.pub-cache/hosted/pub.dev/path_provider_foundation-2.3.1/
[   +1 ms] Found plugin path_provider_linux at
/home/francesco/.pub-cache/hosted/pub.dev/path_provider_linux-2.2.1/
[   +2 ms] Found plugin path_provider_windows at
/home/francesco/.pub-cache/hosted/pub.dev/path_provider_windows-2.2.1/
[   +5 ms] Found plugin screen_brightness at
/home/francesco/.pub-cache/hosted/pub.dev/screen_brightness-0.2.2+1/
[        ] Found plugin screen_brightness_android at
/home/francesco/.pub-cache/hosted/pub.dev/screen_brightness_android-0.1.0+2/
[   +1 ms] Found plugin screen_brightness_ios at
/home/francesco/.pub-cache/hosted/pub.dev/screen_brightness_ios-0.1.0/
[   +1 ms] Found plugin screen_brightness_macos at
/home/francesco/.pub-cache/hosted/pub.dev/screen_brightness_macos-0.1.0+1/
[   +2 ms] Found plugin screen_brightness_windows at
/home/francesco/.pub-cache/hosted/pub.dev/screen_brightness_windows-0.1.3/
[   +7 ms] Found plugin volume_controller at
/home/francesco/.pub-cache/hosted/pub.dev/volume_controller-2.0.7/
[   +1 ms] Found plugin wakelock_plus at
/home/francesco/.pub-cache/hosted/pub.dev/wakelock_plus-1.1.3/
[   +3 ms] Found plugin media_kit_libs_android_video at
/home/francesco/Desktop/media-kit-main/libs/android/media_kit_libs_android_video
/
[   +1 ms] Found plugin media_kit_libs_ios_video at
/home/francesco/Desktop/media-kit-main/libs/ios/media_kit_libs_ios_video/
[   +1 ms] Found plugin media_kit_libs_linux at
/home/francesco/Desktop/media-kit-main/libs/linux/media_kit_libs_linux/
[        ] Found plugin media_kit_libs_macos_video at
/home/francesco/Desktop/media-kit-main/libs/macos/media_kit_libs_macos_video/
[   +1 ms] Found plugin media_kit_libs_windows_video at
/home/francesco/Desktop/media-kit-main/libs/windows/media_kit_libs_windows_video
/
[   +1 ms] Found plugin media_kit_native_event_loop at
/home/francesco/Desktop/media-kit-main/media_kit_native_event_loop/
[   +1 ms] Found plugin media_kit_video at
/home/francesco/Desktop/media-kit-main/media_kit_video/
[  +15 ms] gen_dart_plugin_registrant: Complete
[   +1 ms] Skipping target: _composite
[   +3 ms] complete
[   +7 ms] Launching lib/main.dart on Linux in debug mode...
[   +6 ms] /home/francesco/Developer/flutter/bin/cache/dart-sdk/bin/dart
--disable-dart-dev
/home/francesco/Developer/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_serv
er.dart.snapshot --sdk-root
/home/francesco/Developer/flutter/bin/cache/artifacts/engine/common/flutter_patc
hed_sdk/ --incremental --target=flutter --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true
-DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/767d8c75e8
98091b925519803830fc2721658d07/ --output-dill
/tmp/flutter_tools.UELCWI/flutter_tool.ASXBAE/app.dill --packages
/home/francesco/Desktop/media-kit-main/media_kit_test/.dart_tool/package_config.
json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill
build/9849d3fde14f8238bc82d80453267a41.cache.dill.track.dill --source
file:///home/francesco/Desktop/media-kit-main/media_kit_test/.dart_tool/flutter_
build/dart_plugin_registrant.dart --source
package:flutter/src/dart_plugin_registrant.dart
-Dflutter.dart_plugin_registrant=file:///home/francesco/Desktop/media-kit-main/m
edia_kit_test/.dart_tool/flutter_build/dart_plugin_registrant.dart
--verbosity=error --enable-experiment=alternative-invalidation-strategy
[  +33 ms] Building Linux application...
[  +26 ms] <- compile package:media_kit_test/main.dart
[   +5 ms] executing: [build/linux/x64/debug/] cmake -G Ninja
-DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64
/home/francesco/Desktop/media-kit-main/media_kit_test/linux
[ +258 ms] -- The CXX compiler identification is Clang 14.0.0
[  +12 ms] -- Detecting CXX compiler ABI info
[ +140 ms] -- Detecting CXX compiler ABI info - failed
[        ] -- Check for working CXX compiler: /usr/bin/clang++
[ +143 ms] -- Check for working CXX compiler: /usr/bin/clang++ - broken
[        ] -- Configuring incomplete, errors occurred!
[        ] See also
"/home/francesco/Desktop/media-kit-main/media_kit_test/build/linux/x64/debug/CMa
keFiles/CMakeOutput.log".
[        ] See also
"/home/francesco/Desktop/media-kit-main/media_kit_test/build/linux/x64/debug/CMa
keFiles/CMakeError.log".
[   +2 ms] CMake Error at
/usr/share/cmake-3.22/Modules/CMakeTestCXXCompiler.cmake:62 (message):
[   +4 ms]   The C++ compiler
[        ]     "/usr/bin/clang++"
[        ]   is not able to compile a simple test program.
[        ]   It fails with the following output:
[        ]     Change Dir:
/home/francesco/Desktop/media-kit-main/media_kit_test/build/linux/x64/debug/CMak
eFiles/CMakeTmp
[        ]     Run Build Command(s):/usr/bin/ninja cmTC_ae792 && [1/2] Building
CXX object CMakeFiles/cmTC_ae792.dir/testCXXCompiler.cxx.o
[        ]     [2/2] Linking CXX executable cmTC_ae792
[        ]     FAILED: cmTC_ae792 
[        ]     : && /usr/bin/clang++
CMakeFiles/cmTC_ae792.dir/testCXXCompiler.cxx.o -o cmTC_ae792   && :
[        ]     /usr/bin/ld: cannot find -lstdc++: No such file or directory
[        ]     clang: error: linker command failed with exit code 1 (use -v to
see invocation)
[        ]     ninja: build stopped: subcommand failed.
[        ]   CMake will not be able to correctly generate this project.
[        ] Call Stack (most recent call first):
[        ]   CMakeLists.txt:3 (project)
[  +38 ms] Building Linux application... (completed in 609ms)
[+27926 ms] Exception: Unable to generate build files
[   +1 ms] "flutter run" took 31,617ms.
[   +5 ms] 
           #0      throwToolExit
(package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand
           (package:flutter_tools/src/commands/run.dart:760:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand
(package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure>
           (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[  +92 ms] ensureAnalyticsSent: 85ms
[        ] Running 1 shutdown hook
[  +20 ms] Shutdown hooks complete
[        ] exiting with code 1

`

</details>
