### ISSUE TITLE
dart callbacks from thread, use NativeCallable

### ISSUE THREAD

**Issue by sgehrman** [media-kit/media-kit#556]
I saw your readme talking about callback from a thread.  It's fixed in dart 3.1

see comment on https://github.com/dart-lang/sdk/issues/37022

@Since('3.1')
final class NativeCallable<T extends Function> {
  /// Constructs a [NativeCallable] that can be invoked from any thread.
  ///

A https://github.com/dart-lang/sdk/issues/37022 has been that it does not support async callbacks from another thread. Learn more about this at: https://github.com/dart-lang/sdk/issues/37022. Following situation will explain better:

If you pass a function pointer from Dart to C code, you can invoke it fine. But, as soon as you invoke it from some other thread on the native side, Dart VM will instantly crash. This feature is important because most events take place on a background thread.

**Comment by alexmercerind** [comment]
Hi @sgehrman,

Thanks a lot for pointing this out. I happen to be already aware of the new feature.

I decided to keep it as it is due to following reasons:
- Backward compatibility with older Flutter & Dart SDKs.
- Reasonable improvements provided by the current workaround package: [package: media_kit_native_event_loop](https://github.com/media-kit/media-kit/tree/main/media_kit_native_event_loop).
  - Dispose of all `Player`s on hot-restart.
  - Graceful process termination.
  - Support for higher number of concurrent `Player` instances.

**Comment by alexmercerind** [comment]
The section in README was written during early stage development; it's very stable at present state.
