### ISSUE TITLE
libmpv - why so small? is it lgpl?

### ISSUE THREAD

**Issue by Dingo64** [media-kit/media-kit#669]
How is libmpv's DLL so small? It usually is about 100 MB in other projects. Is it compiled without GPL code?

**Comment by zhongfly** [comment]
https://github.com/media-kit/libmpv-win32-video-cmake/blob/main/packages/mpv.cmake#L27
looklike lgpl

**Comment by Dingo64** [comment]
Thanks @zhongfly !

Calling property value 'mpv-configuration' gives me '--enable-lgpl' as one of the options so that's good.

Overall- a pretty great thing. For some reason screenshots don't work ('screenshot-to-file' command), which would be great and video filters are gone.

**Comment by alexmercerind** [comment]
Hi!

My builds are highly stripped & LGPL, following variants are available:
- video-full
- video-default
- audio-full
- audio-default

Only *-default are available for Windows. You need --enable-encoder={*jpeg*,png} for screenshots to work.

https://github.com/media-kit/libmpv-win32-video-build/releases
https://github.com/media-kit/libmpv-win32-audio-build/releases

I'll most likely ship them by default, I need them somewhere.

**Comment by alexmercerind** [comment]
I use setup from @ shinchiro & @ zhongfly to cross-compile Windows binaries.

**Comment by Dingo64** [comment]
Can I use different file formats for screenshots and not recompile anything?

**Comment by alexmercerind** [comment]
Currently, no image encoders are present to support `screenshot-to-file` sadly.

That's primarily because media_kit has built-in screenshot implementation:
https://github.com/media-kit/media-kit?tab=readme-ov-file#capture-screenshot

A solution can be to retrieve screenshot as pixel-buffer using [`screenshot-raw`](https://mpv.io/manual/stable/#command-interface-screenshot-raw) and manually encode it to JPEG/PNG e.g. using [stb_image.h](https://github.com/nothings/stb) or etc. (different platforms have different APIs available).

**Comment by Dingo64** [comment]
Sounds promising, thanks. How about video filters? Any chance for them in the build?
