### ISSUE TITLE
Plugin doesn't work properly with airplay and chromecast plugins

### ISSUE THREAD

**Issue by sorgfal** [media-kit/media-kit#721]
Now there are several plugins for sharing the screen to another device and they work fine with video player, but cannot work with media kit. Can we somehow fix this? The community does not have enough knowledge in the project to understand the differences in how these solutions are integrated.

**Comment by zezo357** [comment]
please provide as much details as possible 

the devices/versions and explain the problem with images/video if possible

**Comment by sorgfal** [comment]
versions:
media_kit: ^1.1.10                             
media_kit_video: ^1.2.4                        
media_kit_libs_video: ^1.0.4            

devices: any

Explanation:
I have developed some player in my application. I used media_kit to render the video.
I'm using the flutter_to_airplay plugin to share a video to the screen. But when using this plugin, nothing simply happens. The plugin does not see that any video is being played.
If I use the video_player plugin without changing the code responsible for the airplay: the video playback is correctly transferred to the desired device.

Unfortunately, it is very difficult to capture this in a photo or on camera.

**Comment by alexmercerind** [comment]
Not possible without AVPlayer.

**Comment by alexmercerind** [comment]
#207

**Comment by sorgfal** [comment]
GGWP. Thanks for your hard work and great project. This is possibly the best player for Flutter.

**Comment by alexmercerind** [comment]
Just to not sound blunt:

AirPlay is proprietary technology from Apple. There is little to no documentation as to how it actually works underneath. Last time I checked, few people did reverse engineer-audio support, but no progress for video. Even if one manages to reverse-engineer, dealing with breaking changes (due to use of private APIs & such) will be a pain.

Unfortunately I'm not that talented & neither have that amount of time on my hands (to reverse-engineer).

media_kit uses libmpv on all native platforms. This gives us ability to play a wider range of video/audio formats. However, this is not AVPlayer (the default macOS video/audio player) & thus cannot offer those things.

I did think about providing optional platform specific backends for Android, iOS & macOS. However, I have no resources to make such investment presently.
