### ISSUE TITLE
Not Deleting Temporary Files After Being Created in Memory

### ISSUE THREAD

**Issue by mohammadinfo** [media-kit/media-kit#761]
I'm using the Memory method to read the file, but the problem is that the file created is not deleted. I have sensitive videos and I want them to be stored in RAM, not in the hard drive, but they are not deleted and the file can be easily found. I manually made changes in the package itself and the problem was solved, but I want the package itself to be fixed so that there won't be any issues when transferring the project to other systems. Right now, I have to manually make changes for each system.

**Comment by sevenrats** [comment]
A framework like flutter is not remotely appropriate for the level of security that you are attempting to implement, much of which is simple theatre anyway.  Flutter cannot fight the OS over memory security, and deleting files which you yourself have created is not the job of your video playback library.

**Comment by GleammerRay** [comment]
@sevenrats I believe that they are referring to the memory function provided by mediakit. This function is poorly implemented and, in my opinion, should not be present in the library in the first place, as instead of actually reading contents from memory, it creates a temporary file and reads back from it. The choice of framework is largely irrelevant when discussing basic things such as simple runtime memory usage and file I/O.
