### ISSUE TITLE
Update `msvcp*.dll` Windows libraries to latest version

### ISSUE THREAD

**Issue by SleepySquash** [media-kit/media-kit#947]
Related to https://github.com/media-kit/media-kit/issues/842

As mentioned by many, there's a lot of issues with Microsoft Visual C++ Redistributable libraries being embedded with `media_kit` for Windows builds. It seems that the `ANGLE.7z` archive being downloaded (which contains the libraries) is outdated, as the `msvcp140.dll` library is of 14.20 version (while the 14.40 is the last): https://github.com/alexmercerind/flutter-windows-ANGLE-OpenGL-ES/releases

In our project this caused the conflicts with other native packages utilizing C runtime on Windows. For example, a different package is being linked against the fresh 14.40 version of the C runtime DLL, while the `media_kit` embeds and uses the old 14.20 version of this DLL, which causes application to crash during runtime.

I suggest updating the Microsoft Visual C++ Redistributable libraries used in the `ANGLE.7z` archive, as doing so didn't cause any troubles, bugs or anything, yet fixed the issues with other packages. `media_kit` works flawlessly with the latest 14.40 version, no code should be changed at all. You might get the archive from the forked repository: https://github.com/SleepySquash/media-kit/releases/tag/v1.0.1-angle.

The archive should be uploaded to the https://github.com/alexmercerind/flutter-windows-ANGLE-OpenGL-ES repository as a new release, I suppose? So that in the `libs/windows/media_kit_libs_windows_video/windows/CMakeLists.txt` only the version of `ANGLE_URL` would get changed (and the `ANGLE_MD5`). However, if that repository can't be accessed anymore, then this archive should be hosted from somewhere else.

**Comment by Clushdada** [comment]
How should a user do it?

**Comment by abdelaziz-mahdy** [comment]
I don't know, @alexmercerind is that solvable?

**Comment by alexmercerind** [comment]
I'll remove them altogether. It's on my list.

**Comment by alexmercerind** [comment]
Build against main. Do a `flutter clean` before hand.

**Comment by Clushdada** [comment]
> 针对 main 生成。事先做一个。`flutter clean`

I pulled the latest version and received many errors. The compilation did not pass!  @ksanchez9306 @abdelaziz-mahdy

**Comment by alexmercerind** [comment]
@Clushdada see our CI (which succeeds). Try a `flutter clean`.

**Comment by Clushdada** [comment]
/C:/Users/Crush/AppData/Local/Pub/Cache/git/media-kit-1d83fea6f1d63fb4217dce14bc7722361deef520/media_kit_video/lib/src/subtitle/subtitle_view.dart(137,9): error G5FE39F1E: Type 'TextScaler' not found. [F:\demo_desktop\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/Crush/AppData/Local/Pub/Cache/git/media-kit-1d83fea6f1d63fb4217dce14bc7722361deef520/media_kit/lib/src/player/native/player/real.dart(2549,12): error GE90CF69D: The operator '+' isn't defined for the class 'Pointer<Pointer<Utf8>>'. [F:\demo_desktop\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/Crush/AppData/Local/Pub/Cache/git/media-kit-1d83fea6f1d63fb4217dce14bc7722361deef520/media_kit/lib/src/player/native/utils/native_reference_holder.dart(71,45): error GE90CF69D: The operator '+' isn't defined for the class 'Pointer<IntPtr>'. [F:\demo_desktop\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/Crush/AppData/Local/Pub/Cache/git/media-kit-1d83fea6f1d63fb4217dce14bc7722361deef520/media_kit/lib/src/player/native/utils/native_reference_holder.dart(91,47): error GE90CF69D: The operator '+' isn't defined for the class 'Pointer<IntPtr>'. [F:\demo_desktop\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/Crush/AppData/Local/Pub/Cache/git/media-kit-1d83fea6f1d63fb4217dce14bc7722361deef520/media_kit/lib/src/player/native/utils/native_reference_holder.dart(107,47): error GE90CF69D: The operator '+' isn't defined for the class 'Pointer<IntPtr>'. [F:\demo_desktop\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/Crush/AppData/Local/Pub/Cache/git/media-kit-1d83fea6f1d63fb4217dce14bc7722361deef520/media_kit_video/lib/src/subtitle/subtitle_view.dart(111,15): error GC6690633: No named parameter with the name 'textScaler'. [F:\demo_desktop\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/Crush/AppData/Local/Pub/Cache/git/media-kit-1d83fea6f1d63fb4217dce14bc7722361deef520/media_kit_video/lib/src/subtitle/subtitle_view.dart(97,13): error G4127D1E8: The getter 'TextScaler' isn't defined for the class 'SubtitleViewState'. [F:\demo_desktop\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/Crush/AppData/Local/Pub/Cache/git/media-kit-1d83fea6f1d63fb4217dce14bc7722361deef520/media_kit_video/lib/src/subtitle/subtitle_view.dart(137,9): error GACB5210B: 'TextScaler' isn't a type. [F:\demo_desktop\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/Crush/AppData/Local/Pub/Cache/git/media-kit-1d83fea6f1d63fb4217dce14bc7722361deef520/media_kit/lib/ffi/src/utf16.dart(59,31): error GE90CF69D: The operator '+' isn't defined for the class 'Pointer<Uint16>'. [F:\demo_desktop\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/Crush/AppData/Local/Pub/Cache/git/media-kit-1d83fea6f1d63fb4217dce14bc7722361deef520/media_kit_video/lib/media_kit_video_controls/src/controls/widgets/fullscreen_inherited_widget.dart(64,12): error GE5CFE876: The method 'PopScope' isn't defined for the class '_FullscreenInheritedWidgetPopScopeState'. [F:\demo_desktop\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/Crush/AppData/Local/Pub/Cache/git/media-kit-1d83fea6f1d63fb4217dce14bc7722361deef520/media_kit/lib/src/player/native/core/initializer.dart(57,58): error G7A35AD16: listener expects a static function as parameter. dart:ffi only supports calling static Dart functions from native code. Closures and tear-offs are not supported because they can capture context. [F:\demo_desktop\build\windows\flutter\flutter_assemble.vcxproj]
f:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): error MSB8066: “F:\demo_desktop\build\windows\CMakeFiles\41d65ccb45828a50ce8a75ed41eb8a05\flutter_windows.dll.rule;F:\demo_desktop\build\windows\CMakeFiles\4b79cfbbd8120f1ae082e2af87687f7e\flutter_assemble.rule;F:\demo_desktop\windows\flutter\CMakeLists.txt”的自定义生成已退出，代码为 1。 [F:\demo_desktop\build\windows\flutter\flutter_assemble.vcxproj]

**Comment by Clushdada** [comment]
> @Clushdada see our CI (which succeeds). Try a .`flutter clean`



> see our CI (which succeeds). Try a .`flutter clean`

I executed flutter clean and it still works like this

**Comment by alexmercerind** [comment]
https://docs.flutter.dev/release/breaking-changes/deprecate-textscalefactor

**Comment by Clushdada** [comment]
> https://docs.flutter.dev/release/breaking-changes/deprecate-textscalefactor

How can I return the plugin to the previous version? The current project is not yet ready to upgrade to the latest version of Flutter

**Comment by alexmercerind** [comment]
@Clushdada 

Maybe you can pass `ref: 1bd5330cde814d82019e11c72ef54be709c099bd` instead of `ref: main` in your `pubspec.yaml`.

Note that we do not have a maintenance plan for older versions of the plugin... I am lack time for this, all this is made in the AMs.

**Comment by alexmercerind** [comment]
Solved @Clushdada ?

**Comment by Clushdada** [comment]
> Solved @Clushdada ?

f:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: 命令“setlocal [F:\demo_desktop\build\windows\x64\INSTALL.vcxproj]
f:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: "F:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -DBUILD_TYPE=Debug -P cmake_install.cmake [F:\demo_desktop\build\windows\x64\INSTALL.vcxproj]
f:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [F:\demo_desktop\build\windows\x64\INSTALL.vcxproj]
f:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: :cmEnd [F:\demo_desktop\build\windows\x64\INSTALL.vcxproj]
f:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [F:\demo_desktop\build\windows\x64\INSTALL.vcxproj]
f:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: :cmErrorLevel [F:\demo_desktop\build\windows\x64\INSTALL.vcxproj]
f:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: exit /b %1 [F:\demo_desktop\build\windows\x64\INSTALL.vcxproj]
f:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: :cmDone [F:\demo_desktop\build\windows\x64\INSTALL.vcxproj]
f:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [F:\demo_desktop\build\windows\x64\INSTALL.vcxproj]
f:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: :VCEnd”已退出，代码为 1。 [F:\demo_desktop\build\windows\x64\INSTALL.vcxproj]
Error: Build process failed.

**Comment by Clushdada** [comment]
@alexmercerind I have upgraded to the latest version of Flutter and now it prompts these

**Comment by alexmercerind** [comment]
@Clushdada 

Please do a `flutter clean` & use dependency as follows:

```yaml
dependencies:
  media_kit:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: main
      path: ./media_kit
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: main
      path: ./media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: main
      path: ./libs/universal/media_kit_libs_video

dependency_overrides:
  media_kit:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: main
      path: ./media_kit
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: main
      path: ./media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: main
      path: ./libs/universal/media_kit_libs_video
```

Also ensure that the version in your `pubspec.lock` is at latest ref i.e. `88c49c6c0f6187a131a4053f0f1a3a42f2922a8a`.

**Comment by Clushdada** [comment]
> @Clushdada
> 
> Please do a `flutter clean` & use dependency as follows:
> 
> ```yaml
> dependencies:
>   media_kit:
>     git:
>       url: https://github.com/media-kit/media-kit.git
>       ref: main
>       path: ./media_kit
>   media_kit_video:
>     git:
>       url: https://github.com/media-kit/media-kit.git
>       ref: main
>       path: ./media_kit_video
>   media_kit_libs_video:
>     git:
>       url: https://github.com/media-kit/media-kit.git
>       ref: main
>       path: ./libs/universal/media_kit_libs_video
> 
> dependency_overrides:
>   media_kit:
>     git:
>       url: https://github.com/media-kit/media-kit.git
>       ref: main
>       path: ./media_kit
>   media_kit_video:
>     git:
>       url: https://github.com/media-kit/media-kit.git
>       ref: main
>       path: ./media_kit_video
>   media_kit_libs_video:
>     git:
>       url: https://github.com/media-kit/media-kit.git
>       ref: main
>       path: ./libs/universal/media_kit_libs_video
> ```
> 
> Also ensure that the version in your `pubspec.lock` is at latest ref i.e. `88c49c6c0f6187a131a4053f0f1a3a42f2922a8a`.

good

**Comment by PumpkinJuce** [comment]
Hello @SleepySquash I downloaded your 7z archive and tried to change your url to mine, but it didn't work and I got an error

https://github.com/PumpkinJuce/Deals/releases/tag/angel_test

Can you help me with that?

**Comment by SleepySquash** [comment]
@PumpkinJuce, hello there. This issue seems to be resolved, so there's no need to update the libraries. Look at the discussion above.

**Comment by PumpkinJuce** [comment]
Hello, I saw it, but I really need version *.40 (media kit has *.30)

вт, 18 февр. 2025 г., 16:07 Nikita ***@***.***>:

**Comment by PumpkinJuce** [comment]
Could you please help me with that?

вт, 18 февр. 2025 г., 16:41 Мария Лебедева ***@***.***>:
